project:
  title: "dss2024"

editor: visual

title: "dss2024"
css: styles/apa.css
biblio-files:
  - ../references.bib
format:
  html:
    code-fold: true
    toc: false
    toc-depth: 3
    self-contained: true
  pdf:
    number-sections: false
    latex-engine: lualatex
    page-layout:
       margin-left: 1in
       margin-right: 1in
    paper-size: "letter"
    documentclass: "article"
    geometry: "left=1in,right=1in,top=1in,bottom=1in"
    header-includes:
      - \usepackage{footnote}
      - \usepackage{setspace}
      - \usepackage{geometry}
      - \geometry{paperheight=14in}
