---
title: "Brief auf Sommerschule 2024"
author: "Jason Wilby"
date: "May 17, 2024"
---

Liebe Sommerschule-Leute,

Grüße & Willkommen zur Sommerschule!

Ich habe schon mit vielen von euch individuell gesprochen oder gemailt, aber ich wollte euch zusammen nochmal herzlich begrüßen und zum diesjährigen Programm willkommen heißen! 

Ich freue mich sehr auf das Programm und darauf, euch besser kennenzulernen und mit euch zu arbeiten.

Nächste Woche werde ich das "Programmheft" (Info zu den Klassen, driving directions & when to arrive, etc. on the first day) bereitstellen und an euch schicken, und kurz danach den Plan für die Anreise (car-pooling info, airport ride info, etc.).

Heute wollte ich euch zu unserem 2024 Wiki einladen. Bald kommt ihr eine Mail mit Link, um der Seite beizutreten [**dies ist nicht required, aber hilfreich]. Bitte sag Bescheid, wenn du keinen Link bekommst! 

Einige Personen haben gefragt, was sie vor der Sommerschule als Übung machen könnten. Ich kann euch ein Paar Podcasts und Nachrichtenseiten empfehlen. Es hilft sicherlich, z.B. jeden Tag ein Podcast zu hören oder einen Artikel zu lesen und neues Vokabular zu lernen!

[Mein Lieblingspodcast: Radio Wissen: Hier klicken](https://www.br.de/radio/bayern2/sendungen/radiowissen/index.html)

[Deutsche Welle Nachrichten: Heir klicken](https://www.dw.com/de/themen/s-9077)

[Podcast-Listen: Hier klicken](https://podwatch.io/charts/)

Falls ihr noch Fragen habt, bitte mailt, simst oder ruft mich an!

Bis bald,
Jason 
(Handy: 949-468-7881)


Jason Wilby, Ph.D.  
Principal Lecturer of German & LCL Director of Undergraduate Studies  
Chapter President, NM AATG (American Association of Teachers of German)   
Chair, Faculty Senate Admissions and Registration Committee  
Adviser, Languages degrees  
Department of Languages, Cultures and Literatures  
Ortega Hall 311  
MSC 03 2080  
University of New Mexico  
Albuquerque, NM 87131-0001  
(505) 277-4771  

Office Hours: Wednesday 9:00-10:30, Thursday 12:00-13:30, or by appointment.  

Visit the German Summer School:  
http://germansummerschool.unm.edu/  
https://www.facebook.com/diesommerschule/  


